FROM arm64v8/debian:bullseye
RUN apt-get update && apt-get -y install git build-essential wget procps python3-pip cmake
RUN pip3 install awscli
RUN git clone https://github.com/steineggerlab/foldseek.git
RUN cd foldseek && cmake . && make -j 4 && mv src/foldseek /usr/local/bin/
RUN rm -fr foldseek